import type { Client, ConstructionEvent, ConstructionObject, Offer, WorkTask } from './contracts'

export const mockClients: Client[] = [
  {
    id: 'c-101',
    name: 'Анна Смирнова',
    initials: 'АС',
    phone: '+7 905 214-18-42',
    email: 'a.smirnova@example.ru',
    property: '2-комн. · 61,4 м² · № 184',
    project: 'Квартал «Северный» · корпус 2',
    apartmentId: 'apt-184',
    stage: 'Переговоры',
    probability: 72,
    nextAction: 'Согласовать вариант с отделкой',
    nextActionAt: 'Сегодня, 12:30',
    lastContactAt: 'Сегодня, 09:42',
    budget: 'до 9,8 млн ₽',
    preferences: ['2 комнаты', 'этаж 8–14', 'чистовая отделка', 'паркинг'],
    risks: [
      {
        id: 'r-1',
        level: 'warning',
        title: 'Срок отделки под риском',
        detail: 'Поставка дверей смещена на 9 дней. Базовый срок сдачи корпуса не изменён.',
      },
    ],
    conversation: [
      {
        id: 'm-1',
        author: 'client',
        authorName: 'Анна',
        text: 'Важно въехать до начала учебного года. Насколько надёжен срок?',
        occurredAt: 'Сегодня, 09:37',
      },
      {
        id: 'm-2',
        author: 'manager',
        authorName: 'Михаил',
        text: 'Проверю актуальный график и вернусь с вариантами сегодня.',
        occurredAt: 'Сегодня, 09:42',
      },
      {
        id: 'm-3',
        author: 'ai',
        authorName: 'AI-помощник',
        text: 'Возражение связано не с ценой, а с уверенностью в сроке. Покажите контрольные этапы и предложите корпус 1 как резервный вариант.',
        occurredAt: 'Сегодня, 09:43',
      },
    ],
  },
  {
    id: 'c-102',
    name: 'Дмитрий Орлов',
    initials: 'ДО',
    phone: '+7 921 310-77-08',
    email: 'd.orlov@example.ru',
    property: '3-комн. · 78,9 м² · № 241',
    project: 'Квартал «Северный» · корпус 3',
    apartmentId: 'apt-241',
    stage: 'Бронь',
    probability: 88,
    nextAction: 'Получить согласование скидки',
    nextActionAt: 'Сегодня, 14:00',
    lastContactAt: 'Вчера, 18:10',
    budget: 'до 13,5 млн ₽',
    preferences: ['3 комнаты', 'вид во двор', 'кладовая'],
    risks: [
      {
        id: 'r-2',
        level: 'critical',
        title: 'Скидка выше лимита',
        detail: 'Запрошено 4,5%; доступный лимит менеджера — 3%.',
      },
    ],
    conversation: [],
  },
  {
    id: 'c-103',
    name: 'Елена Белова',
    initials: 'ЕБ',
    phone: '+7 911 840-02-16',
    email: 'e.belova@example.ru',
    property: '1-комн. · 39,2 м² · № 68',
    project: 'Дом «Речной»',
    apartmentId: 'apt-68',
    stage: 'Подбор',
    probability: 54,
    nextAction: 'Отправить подборку из 3 вариантов',
    nextActionAt: 'Сегодня, 16:20',
    lastContactAt: 'Вчера, 12:24',
    budget: 'до 7,1 млн ₽',
    preferences: ['1 комната', 'рядом с парком', 'без отделки'],
    risks: [],
    conversation: [],
  },
  {
    id: 'c-104',
    name: 'Илья Волков',
    initials: 'ИВ',
    phone: '+7 903 116-44-39',
    email: 'i.volkov@example.ru',
    property: '2-комн. · 58,1 м² · № 109',
    project: 'Квартал «Северный» · корпус 1',
    apartmentId: 'apt-109',
    stage: 'Оформление',
    probability: 95,
    nextAction: 'Проверить пакет документов',
    nextActionAt: 'Завтра, 10:00',
    lastContactAt: '2 сен, 17:05',
    budget: 'до 10,2 млн ₽',
    preferences: ['2 комнаты', 'ипотека', 'паркинг'],
    risks: [],
    conversation: [],
  },
  {
    id: 'c-105',
    name: 'Мария Котова',
    initials: 'МК',
    phone: '+7 999 620-31-55',
    email: 'm.kotova@example.ru',
    property: '2-комн. · 64,8 м² · № 156',
    project: 'Дом «Речной»',
    apartmentId: 'apt-156',
    stage: 'Новый',
    probability: 31,
    nextAction: 'Уточнить параметры подбора',
    nextActionAt: '8 сен, 11:30',
    lastContactAt: '5 сен, 15:18',
    budget: 'не указан',
    preferences: ['семейная ипотека'],
    risks: [],
    conversation: [],
  },
]

export const mockTasks: WorkTask[] = [
  {
    id: 't-1',
    kind: 'risk',
    title: 'Сообщить об изменении графика',
    context: 'Анна Смирнова · корпус 2',
    dueAt: '12:30',
    clientId: 'c-101',
    priority: 'critical',
    completed: false,
  },
  {
    id: 't-2',
    kind: 'approval',
    title: 'Запросить скидку 4,5%',
    context: 'Дмитрий Орлов · КП-2048',
    dueAt: '14:00',
    clientId: 'c-102',
    priority: 'warning',
    completed: false,
  },
  {
    id: 't-3',
    kind: 'offer',
    title: 'Подготовить подборку',
    context: 'Елена Белова · 3 квартиры',
    dueAt: '16:20',
    clientId: 'c-103',
    priority: 'stable',
    completed: false,
  },
  {
    id: 't-4',
    kind: 'call',
    title: 'Проверить документы',
    context: 'Илья Волков · сделка 98%',
    dueAt: 'Завтра',
    clientId: 'c-104',
    priority: 'stable',
    completed: false,
  },
]

export const mockConstructionEvents: ConstructionEvent[] = [
  {
    id: 'e-1',
    objectId: 'o-2',
    project: 'Квартал «Северный»',
    object: 'Корпус 2',
    title: 'Поставка дверных блоков +9 дней',
    impact: 'Риск для графика чистовой отделки, срок корпуса пока без изменений',
    affectedClients: 6,
    detectedAt: '08:35',
    level: 'warning',
  },
  {
    id: 'e-2',
    objectId: 'o-3',
    project: 'Квартал «Северный»',
    object: 'Корпус 3',
    title: 'Монолит 14 этажа завершён',
    impact: 'Этап закрыт на 2 дня раньше плана',
    affectedClients: 0,
    detectedAt: '07:50',
    level: 'stable',
  },
  {
    id: 'e-3',
    objectId: 'o-5',
    project: 'Дом «Речной»',
    object: 'Паркинг',
    title: 'Остаток машино-мест обновлён',
    impact: 'В продаже осталось 12 мест, спрос выше недельного прогноза',
    affectedClients: 4,
    detectedAt: 'Вчера',
    level: 'critical',
  },
]

export const mockObjects: ConstructionObject[] = [
  {
    id: 'o-1',
    projectId: 'north',
    buildingId: 'north-1',
    name: 'Северный · корпус 1',
    type: 'Корпус',
    readiness: 86,
    plannedDelivery: 'IV кв. 2026',
    forecastDelivery: 'IV кв. 2026',
    availableUnits: 34,
    reservedUnits: 18,
    level: 'stable',
    currentStage: 'Внутренняя отделка',
  },
  {
    id: 'o-2',
    projectId: 'north',
    buildingId: 'north-2',
    name: 'Северный · корпус 2',
    type: 'Корпус',
    readiness: 64,
    plannedDelivery: 'I кв. 2027',
    forecastDelivery: 'I кв. 2027',
    availableUnits: 51,
    reservedUnits: 23,
    level: 'warning',
    currentStage: 'Фасад и инженерные сети',
  },
  {
    id: 'o-3',
    projectId: 'north',
    buildingId: 'north-3',
    name: 'Северный · корпус 3',
    type: 'Корпус',
    readiness: 38,
    plannedDelivery: 'III кв. 2027',
    forecastDelivery: 'III кв. 2027',
    availableUnits: 79,
    reservedUnits: 16,
    level: 'stable',
    currentStage: 'Монолитные работы',
  },
  {
    id: 'o-4',
    projectId: 'river',
    buildingId: 'river-1',
    name: 'Речной · жилой дом',
    type: 'Корпус',
    readiness: 71,
    plannedDelivery: 'I кв. 2027',
    forecastDelivery: 'II кв. 2027',
    availableUnits: 27,
    reservedUnits: 31,
    level: 'critical',
    currentStage: 'Фасад и благоустройство',
  },
  {
    id: 'o-5',
    projectId: 'river',
    name: 'Речной · паркинг',
    type: 'Паркинг',
    readiness: 77,
    plannedDelivery: 'I кв. 2027',
    forecastDelivery: 'I кв. 2027',
    availableUnits: 12,
    reservedUnits: 38,
    level: 'warning',
    currentStage: 'Инженерные сети',
  },
]

export const mockOffers: Offer[] = [
  {
    id: 'КП-2048',
    clientId: 'c-102',
    clientName: 'Дмитрий Орлов',
    apartmentId: 'apt-241',
    property: '№ 241 · 78,9 м²',
    amount: 12_940_000,
    discount: 4.5,
    status: 'Согласование',
    updatedAt: 'Сегодня, 10:12',
    extras: ['Кладовая'],
  },
  {
    id: 'КП-2047',
    clientId: 'c-101',
    clientName: 'Анна Смирнова',
    apartmentId: 'apt-184',
    property: '№ 184 · 61,4 м²',
    amount: 9_460_000,
    discount: 2,
    status: 'Черновик',
    updatedAt: 'Сегодня, 09:58',
    extras: ['Чистовая отделка', 'Паркинг'],
  },
  {
    id: 'КП-2043',
    clientId: 'c-104',
    clientName: 'Илья Волков',
    apartmentId: 'apt-109',
    property: '№ 109 · 58,1 м²',
    amount: 9_870_000,
    discount: 3,
    status: 'Принято',
    updatedAt: '4 сен, 16:40',
    extras: ['Паркинг'],
  },
  {
    id: 'КП-2039',
    clientId: 'c-103',
    clientName: 'Елена Белова',
    apartmentId: 'apt-68',
    property: '№ 68 · 39,2 м²',
    amount: 6_890_000,
    discount: 1.5,
    status: 'Отправлено',
    updatedAt: '3 сен, 12:15',
    extras: [],
  },
]
