package service

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"backend/internal/domain"
	amqp "github.com/rabbitmq/amqp091-go"
)

var (
	ErrRPCResponseTimeout = errors.New("agent service response timed out")
	ErrRPCFailed          = errors.New("agent service returned error")
	ErrRabbitMQUnavailable = errors.New("rabbitmq broker is currently unavailable")
)

var idCounter uint64

func generateSimpleID(prefix string) string {
	counter := atomic.AddUint64(&idCounter, 1)
	randomBytes := make([]byte, 4)
	_, _ = rand.Read(randomBytes)
	return fmt.Sprintf("%s_%d_%d_%s", prefix, time.Now().UnixMilli(), counter, hex.EncodeToString(randomBytes))
}

type AIAgentService interface {
	SendChatRequest(ctx context.Context, payload domain.AgentChatPayload) (*domain.AgentChatResponseData, error)
	Close() error
}

type aiAgentService struct {
	rabbitURL string
	mu        sync.Mutex
	conn      *amqp.Connection
	ch        *amqp.Channel
}

func NewAIAgentService(rabbitURL string) AIAgentService {
	return &aiAgentService{
		rabbitURL: rabbitURL,
	}
}

func (s *aiAgentService) ensureConnection() (*amqp.Channel, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.conn != nil && !s.conn.IsClosed() && s.ch != nil && !s.ch.IsClosed() {
		return s.ch, nil
	}

	// Connect to RabbitMQ
	conn, err := amqp.Dial(s.rabbitURL)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrRabbitMQUnavailable, err)
	}

	ch, err := conn.Channel()
	if err != nil {
		_ = conn.Close()
		return nil, fmt.Errorf("failed to open channel: %v", err)
	}

	// Ensure exchange 'app.topic' exists
	err = ch.ExchangeDeclare(
		"app.topic", // name
		"topic",     // type
		true,        // durable
		false,       // auto-deleted
		false,       // internal
		false,       // no-wait
		nil,         // arguments
	)
	if err != nil {
		_ = ch.Close()
		_ = conn.Close()
		return nil, fmt.Errorf("failed to declare exchange app.topic: %v", err)
	}

	s.conn = conn
	s.ch = ch
	return s.ch, nil
}

func (s *aiAgentService) SendChatRequest(ctx context.Context, payload domain.AgentChatPayload) (*domain.AgentChatResponseData, error) {
	ch, err := s.ensureConnection()
	if err != nil {
		return nil, err
	}

	requestID := generateSimpleID("req")
	correlationID := generateSimpleID("corr")

	reqEnvelope := domain.AgentChatRequestEnvelope{
		RequestID: requestID,
		Action:    "chat",
		Payload:   payload,
	}

	body, err := json.Marshal(reqEnvelope)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %v", err)
	}

	// Create temporary exclusive callback queue for this RPC
	q, err := ch.QueueDeclare(
		"",    // name (generated by broker)
		false, // durable
		true,  // delete when unused
		true,  // exclusive
		false, // no-wait
		nil,   // arguments
	)
	if err != nil {
		return nil, fmt.Errorf("failed to declare callback queue: %v", err)
	}
	defer func() {
		_, _ = ch.QueueDelete(q.Name, false, false, false)
	}()

	msgs, err := ch.Consume(
		q.Name, // queue
		"",     // consumer
		true,   // auto-ack
		false,  // exclusive
		false,  // no-local
		false,  // no-wait
		nil,    // args
	)
	if err != nil {
		return nil, fmt.Errorf("failed to register consumer: %v", err)
	}

	// Publish to exchange app.topic with routing key agent.chat.request
	err = ch.PublishWithContext(
		ctx,
		"app.topic",           // exchange
		"agent.chat.request",  // routing key
		false,                 // mandatory
		false,                 // immediate
		amqp.Publishing{
			ContentType:   "application/json",
			CorrelationId: correlationID,
			ReplyTo:       q.Name,
			Body:          body,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("failed to publish message: %v", err)
	}

	// Wait for response or timeout
	timeout := 25 * time.Second
	timer := time.NewTimer(timeout)
	defer timer.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-timer.C:
			return nil, ErrRPCResponseTimeout
		case d, ok := <-msgs:
			if !ok {
				return nil, errors.New("callback queue channel closed")
			}

			// Validate correlation_id
			if d.CorrelationId != correlationID {
				continue // not our message
			}

			var respEnvelope domain.AgentChatResponseEnvelope
			if err := json.Unmarshal(d.Body, &respEnvelope); err != nil {
				return nil, fmt.Errorf("failed to parse agent response: %v", err)
			}

			// Validate request_id
			if respEnvelope.RequestID != requestID {
				return nil, fmt.Errorf("request_id mismatch: expected %s, got %s", requestID, respEnvelope.RequestID)
			}

			if !respEnvelope.Success {
				return nil, fmt.Errorf("%w: %v", ErrRPCFailed, respEnvelope.Error)
			}

			if respEnvelope.Data == nil {
				return nil, errors.New("agent response data is empty")
			}

			return respEnvelope.Data, nil
		}
	}
}

func (s *aiAgentService) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.ch != nil && !s.ch.IsClosed() {
		_ = s.ch.Close()
	}
	if s.conn != nil && !s.conn.IsClosed() {
		return s.conn.Close()
	}
	return nil
}
